# Generated by Django 6.0 on 2025-12-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='author_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
